### ISSUE TITLE
Mobile UI improvements 

### ISSUE THREAD

**Issue by OwenMelbz** [nunomaduro/nunomaduro.com#1]
Hey, just checked out your new site and thought would give some padantic feedback 😇 I am only on my phone, so can not attach annotated screenshots!

There’s 2 things I initially noticed on mobile which you could change to improve the vertical rythem of the page.

For example under the hero section and before the next heading, there is a large gap - the size of the gap here corresponds to nothing else on the page, making it look a little out of place.

By replicating the same amount of space to the left/right of the copy as above it, will make it balance better, alternatively if you feel it’s too tight then consider using the same spacing as you have between the paragraphs (specifically on the open source page)

This would also apply for the footer, the spacing between each row, eg Twitter/github logos, the space above them is much more than between them unbalancing it, if you were to make it the same it again would improve the consistency.

The other suggestion is a little more obvious on mobile, on the open source page, you have the number of stars for each repo displaying, however this is very misaligned (maybe a missing image?) at least on the iPhone X.

If you need me to attach screenshots I can do, just gimme a shout :)

**Comment by nunomaduro** [comment]
Thanks @OwenMelbz for reporting this issue,

Unfortunately I don't plan to fix them. Please fell free to open a Pull Request to address them. 👍
